In [1]:
a=[2,4,5]


In [2]:
import math

In [3]:
math.sin(4)

-0.7568024953079282

In [4]:
math.cos(a[1])

-0.6536436208636119

In [5]:
math.sin(a)

TypeError: must be real number, not list

In [6]:
import numpy as np

In [7]:
a1=np.array(a)

In [8]:
a1

array([2, 4, 5])

In [10]:
np.sin(a1)

array([ 0.90929743, -0.7568025 , -0.95892427])

In [11]:
np.cos(a1)

array([-0.41614684, -0.65364362,  0.28366219])

In [12]:
np.tan(a1)

array([-2.18503986,  1.15782128, -3.38051501])

In [13]:
np.abs(a)

array([2, 4, 5])

## Statistics

In [14]:
np.mean(a1)

3.6666666666666665

In [16]:
np.sum(a1)

11

In [17]:
np.max(a1)

5

In [18]:
np.min(a1)

2

In [19]:
np.argmax(a1)

2

In [20]:
a1

array([2, 4, 5])

In [21]:
np.argmin(a1)

0

In [22]:
# aggregate function
np.std(a1)

1.247219128924647

In [23]:
np.var(a1)

1.5555555555555554

In [24]:
np.var(a1,ddof=1)

2.333333333333333

In [25]:
scores=np.random.randint(0,10,10)

In [26]:
scores

array([3, 2, 0, 4, 9, 2, 4, 7, 5, 9])

In [29]:
scores=np.random.randint(0,100,(3,4))

In [30]:
scores ## 3 courses and 4 students

array([[ 7, 52, 67, 61],
       [61, 17, 50,  7],
       [18,  4, 29, 49]])

In [31]:
np.mean(scores)

35.166666666666664

In [32]:
scores.mean()

35.166666666666664

In [35]:
np.median(scores)

39.0

In [36]:
scores.max()

67

In [37]:
scores.min()

4

In [38]:
scores.argmax()

2

## Axis

In [39]:
np.sum(scores)

422

In [40]:
np.sum(scores,axis=0)

array([ 86,  73, 146, 117])

In [41]:
np.sum(scores,axis=1)

array([187, 135, 100])

In [42]:
scores

array([[ 7, 52, 67, 61],
       [61, 17, 50,  7],
       [18,  4, 29, 49]])

In [43]:
np.mean(scores,axis=0)

array([28.66666667, 24.33333333, 48.66666667, 39.        ])

In [44]:
np.argmax(np.mean(scores,axis=0))

2

In [45]:
np.argmin(np.mean(scores,axis=0))

1

In [46]:
a1

array([2, 4, 5])

In [47]:
np.argmax(a1)

2

In [48]:
a1[1]=20

In [49]:
a1

array([ 2, 20,  5])

1

## broadcasting

In [51]:
a1

array([ 2, 20,  5])

In [52]:
a1+2

array([ 4, 22,  7])

In [53]:
a1*3

array([ 6, 60, 15])

In [54]:
x=np.linspace(10,100,7)

In [55]:
x

array([ 10.,  25.,  40.,  55.,  70.,  85., 100.])

In [58]:
y=np.arange(10,100,7)

In [59]:
y

array([10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94])

In [60]:
y=np.arange(10,101,15)

In [61]:
y

array([ 10,  25,  40,  55,  70,  85, 100])

In [62]:
y=np.linspace(20,70,3)

In [63]:
y

array([20., 45., 70.])

In [64]:
x

array([ 10.,  25.,  40.,  55.,  70.,  85., 100.])

In [65]:
y

array([20., 45., 70.])

In [66]:
x+y

ValueError: operands could not be broadcast together with shapes (7,) (3,) 

In [68]:
z=np.random.randint(12,200,9)

In [69]:
z

array([ 85, 144,  45,  38, 182,  51,  50, 167,  71])

In [70]:
y

array([20., 45., 70.])

In [71]:
y+z

ValueError: operands could not be broadcast together with shapes (3,) (9,) 

In [72]:
z1=np.array([4])

In [73]:
z1+z

array([ 89, 148,  49,  42, 186,  55,  54, 171,  75])

In [74]:
z1

array([4])

In [75]:
z

array([ 85, 144,  45,  38, 182,  51,  50, 167,  71])

In [76]:
z

array([ 85, 144,  45,  38, 182,  51,  50, 167,  71])

In [77]:
z.shape

(9,)

In [78]:
z.shape=(3,3)

In [79]:
z

array([[ 85, 144,  45],
       [ 38, 182,  51],
       [ 50, 167,  71]])

In [80]:
y

array([20., 45., 70.])

In [81]:
z+y

array([[105., 189., 115.],
       [ 58., 227., 121.],
       [ 70., 212., 141.]])

In [82]:
y1=y[:2]

In [83]:
y1

array([20., 45.])

In [84]:
y1+z

ValueError: operands could not be broadcast together with shapes (2,) (3,3) 

In [86]:
a1=np.random.randint(1,10,(2,3))

In [87]:
a1

array([[9, 3, 4],
       [4, 7, 3]])

In [88]:
b1=np.random.randint(1,10,(1,3))

In [89]:
b1

array([[8, 6, 1]])

In [90]:
b2=np.random.randint(1,10,(2,1))

In [91]:
b2

array([[9],
       [6]])

In [92]:
a1

array([[9, 3, 4],
       [4, 7, 3]])

In [93]:
a1+b2

array([[18, 12, 13],
       [10, 13,  9]])

In [94]:
b1

array([[8, 6, 1]])

In [95]:
a1+b1

array([[17,  9,  5],
       [12, 13,  4]])

In [96]:
b3=np.random.randint(1,2,(2,2))

In [97]:
b3

array([[1, 1],
       [1, 1]])

In [98]:
a1

array([[9, 3, 4],
       [4, 7, 3]])

In [99]:
a1+b3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [109]:
a2=np.random.randint(2,12,(4,2))

In [110]:
a2

array([[2, 9],
       [3, 3],
       [2, 6],
       [9, 2]])

In [111]:
b3

array([[1, 1],
       [1, 1]])

In [115]:
a2+b3

ValueError: operands could not be broadcast together with shapes (4,2) (2,2) 

In [116]:
b3[1]

array([1, 1])