# Numpy And matplotlib

In [1]:
x=[2,4.7,"4",(2,3)]

In [2]:
x

[2, 4.7, '4', (2, 3)]

In [3]:
type(x[0])

int

In [4]:
type(x[1])

float

In [5]:
type(x[2])

str

In [6]:
type(x[3])

tuple

In [7]:
a=[2,3,4]
b=[3,12,8]

In [8]:
a+b #extending the list or concatenation

[2, 3, 4, 3, 12, 8]

In [9]:
c=[]
for i in range(3):
    c.append(a[i]+b[i])
print(c)
    

[5, 15, 12]


In [10]:
import numpy as np

In [11]:
a1=np.array(a)

In [12]:
a1

array([2, 3, 4])

In [13]:
b1=np.array(b)

In [14]:
b1

array([ 3, 12,  8])

In [15]:
a1+b1

array([ 5, 15, 12])

In [16]:
a1*b1

array([ 6, 36, 32])

In [17]:
a1-b1

array([-1, -9, -4])

In [18]:
a1**b1

array([     8, 531441,  65536], dtype=int32)

In [19]:
a1

array([2, 3, 4])

In [21]:
a1%2

array([0, 1, 0], dtype=int32)

In [20]:
a1//2

array([1, 1, 2], dtype=int32)

## Array attributes

In [23]:
a1.shape

(3,)

In [26]:
c1=np.array([[1,2,4],[4,6,4]])
c1

array([[1, 2, 4],
       [4, 6, 4]])

In [25]:
c1.shape

(2, 3)

In [27]:
a1.ndim

1

In [28]:
c1.ndim

2

In [29]:
a1.size

3

In [30]:
c1.size

6

In [31]:
a1.dtype

dtype('int32')

In [32]:
c1.dtype

dtype('int32')

In [33]:
d=np.array([3,8,1.3])

In [34]:
d

array([3. , 8. , 1.3])

In [35]:
d.dtype

dtype('float64')

## Other ways to form arrays

In [36]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [38]:
np.ones(2,3)

TypeError: Cannot interpret '3' as a data type

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.eye((3,3))

TypeError: 'tuple' object cannot be interpreted as an integer

In [44]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])