
# KNN model

In [1]:
## get the model
from sklearn.neighbors import KNeighborsClassifier


In [4]:
## instantiate the model
model1=KNeighborsClassifier()

In [5]:
model1

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [6]:
## get the dataset
import numpy as np
np.random.seed(20)
weights=np.random.randint(40,120,50)

In [7]:
weights

array([ 55,  68,  49,  60, 115,  62, 111,  74,  80,  66,  56, 102,  56,
        47,  46,  66,  53, 115,  98,  65,  43, 114, 115, 101, 117,  97,
        72,  50,  46, 115,  58,  43, 117,  57,  83,  56,  58, 119,  99,
       111, 115,  69,  85,  46, 103, 118,  64,  58,  73, 118])

In [22]:
np.random.seed(20)
gender=np.random.randint(0,2,50)

In [23]:
gender # 0=>female and 1=>male

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1])

In [ ]:
# weights=feature=independent
# gender= target=label=dependent

In [28]:
X=weights # 2 dimensional array (matrix)
y=gender # 1 dimensional array 
y.ndim

1

In [25]:
## train the model
model1.fit(X,y)

ValueError: Expected 2D array, got 1D array instead:
array=[ 55  68  49  60 115  62 111  74  80  66  56 102  56  47  46  66  53 115
  98  65  43 114 115 101 117  97  72  50  46 115  58  43 117  57  83  56
  58 119  99 111 115  69  85  46 103 118  64  58  73 118].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [29]:
X

array([ 55,  68,  49,  60, 115,  62, 111,  74,  80,  66,  56, 102,  56,
        47,  46,  66,  53, 115,  98,  65,  43, 114, 115, 101, 117,  97,
        72,  50,  46, 115,  58,  43, 117,  57,  83,  56,  58, 119,  99,
       111, 115,  69,  85,  46, 103, 118,  64,  58,  73, 118])

In [40]:
X=X.reshape(-1,1)
X

array([[ 55],
       [ 68],
       [ 49],
       [ 60],
       [115],
       [ 62],
       [111],
       [ 74],
       [ 80],
       [ 66],
       [ 56],
       [102],
       [ 56],
       [ 47],
       [ 46],
       [ 66],
       [ 53],
       [115],
       [ 98],
       [ 65],
       [ 43],
       [114],
       [115],
       [101],
       [117],
       [ 97],
       [ 72],
       [ 50],
       [ 46],
       [115],
       [ 58],
       [ 43],
       [117],
       [ 57],
       [ 83],
       [ 56],
       [ 58],
       [119],
       [ 99],
       [111],
       [115],
       [ 69],
       [ 85],
       [ 46],
       [103],
       [118],
       [ 64],
       [ 58],
       [ 73],
       [118]])

In [37]:
model1.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [43]:
## predict with the model
model1.predict([[40],[56],[50]])

array([0, 1, 0])

In [42]:
model1.predict([[40]])

array([0])